CREATE TABLE VIEWAPPOINTMENT(
	SERIAL_NO INT(100) PRIMARY KEY,
    FULLNAME VARCHAR(30) NOT NULL,
    PHONE_NUMBER VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(150),
    AGE INT(5),
    ADDRESS VARCHAR(100) NOT NULL,
    TRAINER_PREFERENCE ENUM('MALE', 'FEMALE', 'NULL'),
    PHYSIO_REQUIRED ENUM('YES', 'NO') NOT NULL, 
    PACKAGE INT(10),
    FOREIGN KEY(FULL_NAME) REFERENCES POSTAPPOINTMENT(FULL_NAME),
	FOREIGN KEY(PHONE_NUMBER) REFERENCES POSTAPPOINTMENT(PHONE_NUMBER),
	FOREIGN KEY(EMAIL) REFERENCES POSTAPPOINTMENT(EMAIL), 
	FOREIGN KEY(AGE) REFERENCES POSTAPPOINTMENT(AGE),
	FOREIGN KEY(ADDRESS) REFERENCES POSTAPPOINTMENT(ADDRESS_LINE1),
	FOREIGN KEY(FULL_NAME) REFERENCES POSTAPPOINTMENT(ADDRESS_LINE2),
	FOREIGN KEY(TRAINER_PREFERENCE) REFERENCES POSTAPPOINTMENT(TRAINER_PREFERENCE),
    FOREIGN KEY(PHYSIO_REQUIRED) REFERENCES POSTAPPOINTMENT(PHYSIO_REQUIRED),
    FOREIGN KEY(PACKAGE) REFERENCES POSTAPPOINTMENT(PACKAGE)
);

INSERT INTO VIEWAPPOINTMENT VALUES
((1, 'John Fernandes', 1234567890, 'john@gmail.com', 29, 'Churchgate', 'MALE', 'NO', 1000));

CREATE TABLE POSTAPPOINTMENT(
	FULLNAME VARCHAR(30) NOT NULL,
    PHONE_NUMBER VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(150),
	AGE INT(5),
    ADDRESS_LINE1 VARCHAR(100) NOT NULL,
    ADDRESS_LINE2 VARCHAR(100) NOT NULL,
    CITY VARCHAR(20),
    STATE VARCHAR(20), 
    COUNTRY VARCHAR(20), 
    PINCODE INT(20),
    TRAINER_PREFERENCE ENUM('MALE', 'FEMALE', 'NULL'),
    PHYSIO_REQUIRED ENUM('YES', 'NO') NOT NULL, 
    PACKAGE ENUM('ONE-TIME', 'FOUR PER WEEK', 'FIVE PER WEEK'),
    DURATION_IN_WEEKS INT(10),
	TOTAL_AMOUNT INT(30)
);
